name: AZADConnectorDeployment

on:
  workflow_dispatch:
  push:
    branches:
      - development

env:
  AZURE_FUNCTIONAPP_NAME: px-azure-ad-connector   # set this to your application's name
  NODE_VERSION: '16.x' # set this to the node version to use
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Install dependencies
      run: pnpm install

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
